# Generated by Django 2.2.3 on 2020-03-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
